<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\University;

class CambodiaUniversitySeeder extends Seeder
{
    public function run(): void
    {
        $universities = [
            ['name' => 'Royal University of Phnom Penh', 'location' => 'Phnom Penh, Cambodia', 'description' => 'The Royal University of Phnom Penh (RUPP) is Cambodia\'s oldest and most prestigious public university, founded in 1960. It offers a wide range of undergraduate and postgraduate programmes across faculties including science, humanities, social sciences, education, and information technology.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.rupp.edu.kh', 'ranking' => 1, 'admission_requirements' => 'Grade 12 certificate or equivalent. Pass the National Baccalaureate Examination.', 'is_active' => true, 'established_year' => 1960],
            ['name' => 'Royal University of Law and Economics', 'location' => 'Phnom Penh, Cambodia', 'description' => 'The Royal University of Law and Economics (RULE) is a prestigious public university established in 1949. RULE specialises in law, economics, business management, and international relations.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.rule.edu.kh', 'ranking' => 2, 'admission_requirements' => 'National Baccalaureate certificate. Entrance examination in Khmer, French, or English.', 'is_active' => true, 'established_year' => 1949],
            ['name' => 'Institute of Technology of Cambodia', 'location' => 'Phnom Penh, Cambodia', 'description' => 'The Institute of Technology of Cambodia (ITC) is the leading public university for engineering, applied sciences, and technology in Cambodia. Founded in 1964, ITC trains the country\'s top engineers and technology professionals.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.itc.edu.kh', 'ranking' => 3, 'admission_requirements' => 'National Baccalaureate with strong results in mathematics and sciences. Competitive entrance examination.', 'is_active' => true, 'established_year' => 1964],
            ['name' => 'National University of Management', 'location' => 'Phnom Penh, Cambodia', 'description' => 'The National University of Management (NUM) is a leading public university specialising in business, economics, management, and public administration. Established in 1983.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.num.edu.kh', 'ranking' => 4, 'admission_requirements' => 'National Baccalaureate certificate. Entrance examination in business studies and English.', 'is_active' => true, 'established_year' => 1983],
            ['name' => 'Royal University of Agriculture', 'location' => 'Phnom Penh, Cambodia', 'description' => 'The Royal University of Agriculture (RUA) is Cambodia\'s premier public institution dedicated to agricultural science, natural resources, and rural development. Founded in 1964.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.rua.edu.kh', 'ranking' => 5, 'admission_requirements' => 'National Baccalaureate certificate. Priority given to applicants from rural provinces.', 'is_active' => true, 'established_year' => 1964],
            ['name' => 'University of Health Sciences', 'location' => 'Phnom Penh, Cambodia', 'description' => 'The University of Health Sciences (UHS) is Cambodia\'s main public university for medical and health education, established in 1946. UHS trains doctors, nurses, pharmacists, dentists, and other health professionals.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.uhs.edu.kh', 'ranking' => 6, 'admission_requirements' => 'National Baccalaureate with distinction in sciences. Highly competitive entrance examination.', 'is_active' => true, 'established_year' => 1946],
            ['name' => 'University of Battambang', 'location' => 'Battambang, Cambodia', 'description' => 'The University of Battambang (UBB) is a public university serving the northwest region of Cambodia, offering programmes in education, economics, law, information technology, and tourism.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Battambang', 'website' => 'https://www.ubb.edu.kh', 'ranking' => 7, 'admission_requirements' => 'National Baccalaureate certificate. Application form submission.', 'is_active' => true, 'established_year' => 2008],
            ['name' => 'Svay Rieng University', 'location' => 'Svay Rieng, Cambodia', 'description' => 'Svay Rieng University (SRU) is a public university in eastern Cambodia offering programmes in education, law, economics, agriculture, and information technology.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Svay Rieng', 'website' => 'https://www.sru.edu.kh', 'ranking' => 8, 'admission_requirements' => 'National Baccalaureate certificate. Priority for students from eastern provinces.', 'is_active' => true, 'established_year' => 2004],
            ['name' => 'Royal University of Fine Arts', 'location' => 'Phnom Penh, Cambodia', 'description' => 'The Royal University of Fine Arts (RUFA) is Cambodia\'s premier institution for arts, architecture, and cultural heritage, specialising in traditional Khmer arts, architecture, and archaeology. Founded in 1965.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.rufa.edu.kh', 'ranking' => 9, 'admission_requirements' => 'National Baccalaureate certificate. Portfolio submission for fine arts applicants.', 'is_active' => true, 'established_year' => 1965],
            ['name' => 'Prek Leap National School of Agriculture', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Prek Leap National School of Agriculture provides programmes in animal husbandry, crop production, fish farming, and rural development with emphasis on hands-on practical learning.', 'type' => 'public', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.pnsa.edu.kh', 'ranking' => 10, 'admission_requirements' => 'National Baccalaureate certificate or Grade 9 completion for technical programmes.', 'is_active' => true, 'established_year' => 1985],
            ['name' => 'Paññāsāstra University of Cambodia', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Paññāsāstra University of Cambodia (PUC) is one of the most prominent private universities in the country, known for English-language instruction and strong programmes in liberal arts, business, and international relations.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.puc.edu.kh', 'ranking' => 11, 'admission_requirements' => 'High school diploma. English proficiency test. Application with personal statement.', 'is_active' => true, 'established_year' => 1997],
            ['name' => 'American University of Phnom Penh', 'location' => 'Phnom Penh, Cambodia', 'description' => 'The American University of Phnom Penh (AUPP) is the only university in Cambodia providing internationally recognised U.S.-style dual-degree programmes in partnership with accredited universities in the United States.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.aupp.edu.kh', 'ranking' => 12, 'admission_requirements' => 'High school diploma. TOEFL or IELTS score required. Application essay and interview.', 'is_active' => true, 'established_year' => 2013],
            ['name' => 'Build Bright University', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Build Bright University (BBU) is one of Cambodia\'s largest private universities with multiple campuses nationwide, offering affordable higher education in business, education, tourism, IT, and engineering.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.bbu.edu.kh', 'ranking' => 13, 'admission_requirements' => 'National Baccalaureate certificate. No entrance examination required for most programmes.', 'is_active' => true, 'established_year' => 2003],
            ['name' => 'Cambodian Mekong University', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Cambodian Mekong University (CMU) is a private university offering programmes in law, economics, finance, computer science, and management with strong connections to the business community.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.mekong.edu.kh', 'ranking' => 14, 'admission_requirements' => 'High school diploma or equivalent. Interview for some programmes.', 'is_active' => true, 'established_year' => 2000],
            ['name' => 'Paragon International University', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Paragon International University is a modern private university offering internationally recognised programmes in engineering, economics, global affairs, and computer science with strong English-language instruction.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.paragoniu.edu.kh', 'ranking' => 15, 'admission_requirements' => 'High school diploma. English proficiency required. Interview for scholarship applicants.', 'is_active' => true, 'established_year' => 2012],
            ['name' => 'Norton University', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Norton University is a well-established private university offering programmes in management, economics, IT, English, and education with strong emphasis on English-language instruction and practical skills.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.norton.edu.kh', 'ranking' => 16, 'admission_requirements' => 'National Baccalaureate certificate. English placement test upon entry.', 'is_active' => true, 'established_year' => 2003],
            ['name' => 'Phnom Penh International University', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Phnom Penh International University (PPIU) offers undergraduate and graduate programmes in business, law, IT, hospitality, and social sciences with strong emphasis on applied learning and practical skills.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.ppiu.edu.kh', 'ranking' => 17, 'admission_requirements' => 'High school diploma or equivalent. No entrance exam required.', 'is_active' => true, 'established_year' => 2002],
            ['name' => 'Asia Euro University', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Asia Euro University (AEU) is a private university offering programmes in economics, business, IT, law, and tourism. Known for flexibility with evening and weekend classes catering to working students.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.aeu.edu.kh', 'ranking' => 18, 'admission_requirements' => 'National Baccalaureate certificate. Open admission policy for most programmes.', 'is_active' => true, 'established_year' => 2002],
            ['name' => 'Western University', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Western University is a private university in Phnom Penh offering programmes in business administration, accounting, computer science, tourism, and education with a strong focus on accounting and finance.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.western.edu.kh', 'ranking' => 19, 'admission_requirements' => 'National Baccalaureate certificate. Interview for scholarship consideration.', 'is_active' => true, 'established_year' => 2003],
            ['name' => 'Kirirom Institute of Technology', 'location' => 'Kampong Speu, Cambodia', 'description' => 'Kirirom Institute of Technology (KIT) is an innovative full-boarding private university in Kampong Speu focused on software engineering and IT, established in collaboration with Japanese partners.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Kampong Speu', 'website' => 'https://kit.edu.kh', 'ranking' => 20, 'admission_requirements' => 'National Baccalaureate with good results in mathematics. Entrance examination and interview. Full boarding required.', 'is_active' => true, 'established_year' => 2014],
            ['name' => 'University of Southeast Asia', 'location' => 'Siem Reap, Cambodia', 'description' => 'The University of Southeast Asia (USEA) is a private university in Siem Reap offering programmes in business, tourism, hospitality, IT, and English with strong ties to the local tourism industry.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Siem Reap', 'website' => 'https://www.usea.edu.kh', 'ranking' => 21, 'admission_requirements' => 'National Baccalaureate certificate. Interview for hospitality management programme.', 'is_active' => true, 'established_year' => 2000],
            ['name' => 'Beltei International University', 'location' => 'Phnom Penh, Cambodia', 'description' => 'Beltei International University is a private university in Phnom Penh with a strong reputation in teacher training and education. It also runs a network of international schools giving graduates direct employment pathways.', 'type' => 'private', 'country' => 'Cambodia', 'city' => 'Phnom Penh', 'website' => 'https://www.beltei.edu.kh', 'ranking' => 22, 'admission_requirements' => 'National Baccalaureate certificate. Placement test for English language programmes.', 'is_active' => true, 'established_year' => 1999],
        ];

        foreach ($universities as $data) {
            University::updateOrCreate(['name' => $data['name']], $data);
        }

        $this->command->info('✅ Cambodia universities seeded: ' . count($universities) . ' records.');
    }
}
