<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CambodiaUniversitySeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Using Unsplash for reliable cover images (university/campus themed)
        // Using ui-avatars.com for logos (generates initials-based logos, always works)
        $universities = [
            // ── Public ───────────────────────────────────────────────────────
            [
                'name'                  => 'Royal University of Phnom Penh',
                'description'          => 'The oldest and largest public university in Cambodia, offering a wide range of programs in sciences, humanities, and social sciences.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.rupp.edu.kh/',
                'logo'                  => 'http://rupp.edu.kh/images/rupp-logo.png',
                'cover_image'           => 'https://lh3.googleusercontent.com/gps-cs-s/AHVAweqFKs_w-M62tLDwrjS2e7M7BOPJABre99-WKxm6gEu15JcuXxIvnwqj9Hk7Z1_LmZ-ORWmUdVH_F4fheiutmM0tUciL7tUtwEzEHmHOpgLAGXmeO3KuK9tKltpaKB-d81MnUk6y=s1360-w1360-h1020-rw',
                'images'                => json_encode([
                    'https://lh3.googleusercontent.com/gps-cs-s/AHVAweoUOdUVBBIqv2Ju5NE6Hg9oFqowcj7-Au8SvI5OHKSUjrgP0o5oEUTijg7oitz-iinil3eAwSdix4yCP7Yfsk0_jYz1vVL8jN3PWdNkJjdoGh4lSk1c-mvkMXkPmSfrYdrUHkvB=s1360-w1360-h1020-rw',
                    'https://lh3.googleusercontent.com/gps-cs-s/AHVAwepH7o_-aFvCdMbAbFDCUuGxu-VqPTYcERanThA6eNzg-2sFaf7obHy06a2NcThz6UZw_-EIj-7MJiAUu48M6JqgJsAmpL6kmi5JCpqjwDUouv2PDRFHSvaJRfrf69QeV3FHfCUc=s1360-w1360-h1020-rw',
                ]),
                'ranking'               => 1.00,
                'established_year'      => 1960,
                'admission_requirements'=> 'High school diploma with minimum grade C. Entrance exam required for most faculties.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Royal University of Agriculture',
                'description'          => 'Cambodia\'s premier institution for agricultural sciences, natural resources, rural development, and veterinary medicine.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.rua.edu.kh',
                'logo'                  => 'https://www.rua.edu.kh/assets/images/image1.png',
                'cover_image'           => 'https://rua.edu.kh/assets/images/videos/17288966213pPARn6TjM.jpg',
                'images'                => json_encode([]),
                'ranking'               => 2.00,
                'established_year'      => 1964,
                'admission_requirements'=> 'High school diploma. Entrance exam for agricultural and veterinary programs.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Institute of Technology of Cambodia',
                'description'          => 'The leading technical and engineering university in Cambodia, providing education in engineering, architecture, and applied sciences.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.itc.edu.kh',
                'logo'                  => 'https://itc.edu.kh/wp-content/uploads/2021/02/cropped-Logo-ITC.png',
                'cover_image'           => 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=1200&q=80',
                'images'                => json_encode([
                    'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=1200&q=80',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80',
                ]),
                'ranking'               => 3.00,
                'established_year'      => 1964,
                'admission_requirements'=> 'Strong background in mathematics and sciences. Competitive entrance examination.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'National University of Management',
                'description'          => 'Specialises in management, business administration, economics, law, and accounting for Cambodia\'s public sector and industry.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.num.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=NUM&size=200&background=E65100&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 4.00,
                'established_year'      => 1983,
                'admission_requirements'=> 'High school diploma. Admission based on written entrance examination.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'University of Health Sciences',
                'description'          => 'The national institution for medical education in Cambodia, training doctors, pharmacists, nurses, and public health professionals.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.uhs.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=UHS&size=200&background=C62828&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80',
                'images'                => json_encode([
                    'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80',
                    'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=1200&q=80',
                ]),
                'ranking'               => 5.00,
                'established_year'      => 1946,
                'admission_requirements'=> 'Excellent results in sciences (Biology, Chemistry, Physics). Highly competitive entrance exam.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Royal Academy of Cambodia',
                'description'          => 'The national research academy conducting advanced research across humanities, social sciences, natural sciences, and technology.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.rac.gov.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=RAC&size=200&background=4527A0&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1568667256549-094345857637?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 6.00,
                'established_year'      => 1999,
                'admission_requirements'=> 'Postgraduate qualifications required. Selective research-based admission.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'National Technical Training Institute',
                'description'          => 'Provides technical and vocational education to develop Cambodia\'s skilled workforce in engineering and technology.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.ntti.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=NTTI&size=200&background=00695C&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 7.00,
                'established_year'      => 1999,
                'admission_requirements'=> 'Completed grade 12. Practical aptitude test for technical programs.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Preah Kossamak Nursing School',
                'description'          => 'The main nursing education institution under the Ministry of Health, training professional nurses for Cambodia\'s healthcare system.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => null,
                'logo'                  => 'https://ui-avatars.com/api/?name=PKNS&size=200&background=C62828&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 8.00,
                'established_year'      => 1953,
                'admission_requirements'=> 'High school diploma with science subjects. Ministry of Health selection process.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'University of Fine Arts',
                'description'          => 'Cambodia\'s national arts conservatory preserving and promoting traditional Khmer arts, music, dance, and fine arts education.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => null,
                'logo'                  => 'https://ui-avatars.com/api/?name=UFA&size=200&background=6A1B9A&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1200&q=80',
                'images'                => json_encode([
                    'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1200&q=80',
                    'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80',
                ]),
                'ranking'               => 9.00,
                'established_year'      => 1965,
                'admission_requirements'=> 'Audition or portfolio required alongside academic qualifications.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Cambodian Mekong University',
                'description'          => 'A public university in Phnom Penh offering programs in business, education, social sciences, and information technology.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.mekong.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=CMU&size=200&background=1565C0&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 10.00,
                'established_year'      => 2003,
                'admission_requirements'=> 'High school diploma. Interview and entrance assessment.',
                'is_active'             => true,
            ],

            // ── Private ──────────────────────────────────────────────────────
            [
                'name'                  => 'Norton University',
                'description'          => 'One of Cambodia\'s leading private universities, offering internationally recognised programs in IT, business, law, and engineering.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.norton.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=NU&size=200&background=1565C0&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80',
                'images'                => json_encode([
                    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80',
                    'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&q=80',
                ]),
                'ranking'               => 11.00,
                'established_year'      => 1996,
                'admission_requirements'=> 'High school diploma. English proficiency test. No entrance exam required.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'University of Cambodia',
                'description'          => 'A major private university delivering American-style liberal arts education with strong programs in business, law, IT, and social sciences.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.uc.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=UC&size=200&background=E65100&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 12.00,
                'established_year'      => 2003,
                'admission_requirements'=> 'High school diploma or equivalent. Interview with admissions office.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Pannasastra University of Cambodia',
                'description'          => 'A private university known for its English-medium instruction, offering programs in communications, arts, business, and education.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.puc.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=PUC&size=200&background=6A1B9A&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 13.00,
                'established_year'      => 1997,
                'admission_requirements'=> 'High school diploma. English placement test. No entrance exam.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Cambodia University of Technology and Science',
                'description'          => 'Specialises in applied science, engineering, and technology with a strong focus on industry partnerships and practical training.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.cust.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=CUST&size=200&background=0277BD&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 14.00,
                'established_year'      => 2008,
                'admission_requirements'=> 'Science and mathematics background. Admission interview required.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Build Bright University',
                'description'          => 'A growing private university with campuses across Cambodia, offering accessible education in business, IT, law, and social sciences.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.bbu.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=BBU&size=200&background=00695C&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 15.00,
                'established_year'      => 2002,
                'admission_requirements'=> 'High school diploma. Open admission policy for most programs.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Angkor University',
                'description'          => 'Based in Siem Reap, Angkor University serves the northern region with programs in tourism, hospitality, business, and education.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Siem Reap',
                'location'              => 'Siem Reap, Cambodia',
                'website'               => 'https://www.angkor.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=AU&size=200&background=E65100&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 16.00,
                'established_year'      => 2000,
                'admission_requirements'=> 'High school diploma. Interview for tourism and hospitality programs.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Western University',
                'description'          => 'A private institution focused on business, economics, and management with a modern curriculum aligned with ASEAN standards.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.western.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=WU&size=200&background=1565C0&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 17.00,
                'established_year'      => 2003,
                'admission_requirements'=> 'High school diploma. Basic English assessment.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Cambodian University for Specialties',
                'description'          => 'Offers specialised vocational and professional programs in engineering, health sciences, and business administration.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => null,
                'logo'                  => 'https://ui-avatars.com/api/?name=CUS&size=200&background=4527A0&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1534982421995-f6ef66de82e0?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 18.00,
                'established_year'      => 2005,
                'admission_requirements'=> 'High school diploma and relevant vocational background preferred.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Asia Euro University',
                'description'          => 'An internationally oriented private university offering programs in business, IT, media studies, and social sciences.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.aeu.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=AEU&size=200&background=0277BD&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 19.00,
                'established_year'      => 2007,
                'admission_requirements'=> 'High school diploma. English language interview.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Human Resources University',
                'description'          => 'Focuses on developing Cambodia\'s human capital through programs in management, public administration, and social development.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => 'https://www.hru.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=HRU&size=200&background=00695C&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 20.00,
                'established_year'      => 2003,
                'admission_requirements'=> 'High school diploma. Admission interview.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Pannasastra University (Siem Reap)',
                'description'          => 'The Siem Reap campus of Pannasastra University, serving students in the Angkor region with a focus on tourism and the arts.',
                'type'                  => 'private',
                'country'               => 'Cambodia',
                'city'                  => 'Siem Reap',
                'location'              => 'Siem Reap, Cambodia',
                'website'               => 'https://www.puc.edu.kh',
                'logo'                  => 'https://ui-avatars.com/api/?name=PUC&size=200&background=6A1B9A&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 21.00,
                'established_year'      => 2008,
                'admission_requirements'=> 'High school diploma. English placement test.',
                'is_active'             => true,
            ],
            [
                'name'                  => 'Preah Sihanouk Raja Buddhist University',
                'description'          => 'The national Buddhist university promoting Khmer culture, Buddhist philosophy, Pali language, and social studies.',
                'type'                  => 'public',
                'country'               => 'Cambodia',
                'city'                  => 'Phnom Penh',
                'location'              => 'Phnom Penh, Cambodia',
                'website'               => null,
                'logo'                  => 'https://ui-avatars.com/api/?name=PSRBU&size=200&background=E65100&color=fff&bold=true&font-size=0.4',
                'cover_image'           => 'https://images.unsplash.com/photo-1568667256549-094345857637?w=1200&q=80',
                'images'                => json_encode([]),
                'ranking'               => 22.00,
                'established_year'      => 1954,
                'admission_requirements'=> 'Open to Buddhist monks and laypeople with high school diploma.',
                'is_active'             => true,
            ],
        ];

        foreach ($universities as &$u) {
            $u['created_at'] = $now;
            $u['updated_at'] = $now;
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('universities')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('universities')->insert($universities);

        $this->command->info('✅ Seeded ' . count($universities) . ' Cambodia universities with images.');
    }
}